# Generated by Django 5.0.2 on 2025-01-22 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_id_alter_blogauthor_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogAuthor',
            new_name='UserProfile',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(help_text="What's on your mind?", max_length=2000),
        ),
    ]
