# Generated by Django 5.0.2 on 2025-01-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_blogauthor_userprofile_alter_blog_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-upload_time']},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['upload_time']},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='post_date',
            new_name='upload_time',
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='post_date',
            new_name='upload_time',
        ),
    ]
